/*
Script generated by Aqua Data Studio 16.0.0-dev-58 on Dec-04-2014 03:22:02 PM
Database: vbmart
Schema: public
Objects: SEQUENCE, TABLE
*/
DROP TABLE [public].[test_keys]
/
DROP TABLE [public].[test3]
/
DROP TABLE [public].[test]
/
DROP SEQUENCE [public].[sequence1]
/

CREATE SEQUENCE [public].[sequence1]
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START WITH 1
	CACHE 250000
	CYCLE
/
CREATE FLEX TABLE [public].[test]  ( 
	[c1]     	numeric(12,12) 
	)
ORDER BY [c1]
/
CREATE TABLE [public].[test3]  ( 
	[c1]	interval day to hour,
	[c2]	interval day to minute,
	[c3]	interval,
	[c4]	varchar(10),
	[c5]	numeric(12,8) 
	)
/
CREATE TABLE [public].[test_keys]  ( 
	[key_name]       	long varchar,
	[frequency]      	int,
	[data_type_guess]	varchar(200) 
	)
ORDER BY [frequency]
UNSEGMENTED NODE v_vbmart_node0001
/

GRANT SELECT ON SEQUENCE [public].[sequence1] TO [user1] WITH GRANT OPTION
/
GRANT SELECT ON SEQUENCE [public].[sequence1] TO [vertica] WITH GRANT OPTION
/
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON TABLE [public].[test] TO [user1] WITH GRANT OPTION
/
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON TABLE [public].[test] TO [vertica] WITH GRANT OPTION
/
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON TABLE [public].[test3] TO [user1] WITH GRANT OPTION
/
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON TABLE [public].[test3] TO [vertica] WITH GRANT OPTION
/
